/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin

Obsidian Market Proxy Plugin
=============================
Provides network proxy functionality for Obsidian's plugin and theme markets,
specifically designed to accelerate access to GitHub resources.
Supports both desktop and mobile platforms.

Key Features:
- Configurable proxy URLs for multiple GitHub domains
- Real-time URL rewriting for specified website acceleration
- Cross-platform support (Electron & Capacitor)
- Customizable proxy server endpoints
*/

var defineProperty = Object.defineProperty;
var getOwnPropertyDescriptor = Object.getOwnPropertyDescriptor;
var getOwnPropertyNames = Object.getOwnPropertyNames;
var hasOwnProperty = Object.prototype.hasOwnProperty;

// Copy all enumerable properties from source to target
var copyProperties = (target, source) => {
  for (var key in source) 
    defineProperty(target, key, { get: source[key], enumerable: !0 });
};

// Extend derived object with properties from base object
var extendStatics = (derived, base, excludeProperty, descriptor) => {
  if ((base && typeof base == "object") || typeof base == "function")
    for (let propertyName of getOwnPropertyNames(base))
      !hasOwnProperty.call(derived, propertyName) &&
        propertyName !== excludeProperty &&
        defineProperty(derived, propertyName, {
          get: () => base[propertyName],
          enumerable: !(descriptor = getOwnPropertyDescriptor(base, propertyName)) || descriptor.enumerable,
        });
  return derived;
};

// Create ES module wrapper
var createModule = (exportsObj) => 
  extendStatics(defineProperty({}, "__esModule", { value: !0 }), exportsObj);

var obsidian = require("obsidian");

// Default settings with configurable proxy URLs
const DEFAULT_SETTINGS = {
  proxyPrefix: "https://gh-proxy.org/",
  enableLogging: false,
  enableProxy: true,
  // Configurable URLs to proxy - user can add/remove/modify
  proxiedUrls: [
    "https://github.com/",
    "https://raw.githubusercontent.com/",
    "https://api.github.com/",
    "https://objects.githubusercontent.com/"
  ]
};

// Proxy handler for desktop (Electron) environment
var AppProxy = class {
  constructor(settings) {
    this.settings = settings;
    if (window.electron && window.electron.ipcRenderer) {
      window.sendHandle = window.electron.ipcRenderer.send;
    }
  }
  
  register() {
    if (window.electron && window.electron.ipcRenderer && this.settings.enableProxy) {
      const self = this; // Store reference for closure
      window.electron.ipcRenderer.send = function (channel, event, request, ...rest) {
        UrlRewrite(request, self.settings);
        if (window.sendHandle) {
          window.sendHandle(channel, event, request, ...rest);
        }
      };
    }
  }
  
  unRegister() {
    if (window.electron && window.electron.ipcRenderer && window.sendHandle) {
      window.electron.ipcRenderer.send = window.sendHandle;
    }
  }
};

// Proxy handler for mobile (Capacitor) environment
var NativeProxy = class {
  constructor(settings) {
    this.settings = settings;
    if (window.Capacitor && window.Capacitor.toNative) {
      window.sendHandle = window.Capacitor.toNative;
    }
  }
  
  register() {
    if (window.Capacitor && window.Capacitor.toNative && this.settings.enableProxy) {
      const self = this; // Store reference for closure      
      window.toNativeContainer = function () {
        window.Capacitor.toNative = (pluginId, methodName, request, callback) => {
          // Only intercept App.requestUrl calls
          if (pluginId == "App" && methodName == "requestUrl") {
            UrlRewrite(request, self.settings);
          }
          if (window.sendHandle) {
            return window.sendHandle(pluginId, methodName, request, callback);
          }
          return null;
        };
      };
      
      window.toNativeContainer();
    }
  }
  
  unRegister() {
    if (window.Capacitor && window.Capacitor.toNative && window.sendHandle) {
      window.Capacitor.toNative = window.sendHandle;
    }
  }
};

// Check if a request URL needs to be proxied based on configurable URLs
function isNeedUrlRewrite(request, proxiedUrls) {
  if (!request || !request.url || !proxiedUrls || !Array.isArray(proxiedUrls)) {
    return false;
  }
  
  // Check if URL starts with any of the configured prefixes
  for (let urlPrefix of proxiedUrls) {
    if (request.url.startsWith(urlPrefix)) {
      return true;
    }
  }
  
  return false;
}

// Rewrite specified URLs to use proxy server for acceleration
function UrlRewrite(request, settings) {
  if (!settings || !settings.enableProxy) {
    return;
  }
  
  if (request && request.url && isNeedUrlRewrite(request, settings.proxiedUrls)) {
    const src = request.url;
    
    // Normalize proxy prefix to end with slash
    let proxyPrefix = settings.proxyPrefix;
    if (proxyPrefix && !proxyPrefix.endsWith('/')) {
      proxyPrefix += '/';
    }
    
    // Normalize original URL to not start with slash
    let originalUrl = request.url;
    if (originalUrl.startsWith('/')) {
      originalUrl = originalUrl.substring(1);
    }
    
    // Rewrite URL to use proxy for acceleration
    request.url = proxyPrefix + originalUrl;
    
    // Log rewrite activity if enabled
    if (settings.enableLogging) {
      console.log("MarketProxy: URL accelerated via proxy", { 
        original: src, 
        accelerated: request.url,
        proxyServer: proxyPrefix
      });
    }
    
    // Additional logging for Capacitor environment
    if (window.Capacitor && window.Capacitor.isLoggingEnabled) {
      window.console.info(JSON.stringify({ original: src, accelerated: request.url }));
    }
    
    // Add required headers for proxy compatibility
    request.headers || (request.headers = {});
    request.headers["content-type"] = "application/x-www-form-urlencoded";
    request.headers["Access-Control-Allow-Origin"] = "*";
  }
}

// Settings tab for plugin configuration
class MarketProxySettingTab extends obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }

  display() {
    const {containerEl} = this;
    containerEl.empty();

    containerEl.createEl('h2', {text: 'Market Proxy Settings'});
    containerEl.createEl('p', {
      text: 'Configure proxy settings to accelerate access to GitHub resources for Obsidian markets.'
    });

    // Proxy enable/disable toggle
    new obsidian.Setting(containerEl)
      .setName('Enable Proxy')
      .setDesc('Enable or disable the GitHub acceleration proxy functionality.')
      .addToggle(toggle => toggle
        .setValue(this.plugin.settings.enableProxy)
        .onChange(async (value) => {
          this.plugin.settings.enableProxy = value;
          await this.plugin.saveSettings();
          // Reinitialize proxy with new setting
          if (this.plugin.proxy) {
            this.plugin.proxy.unRegister();
            this.plugin.proxy = null;
          }
          if (value) {
            this.plugin.initProxy();
          }
        }));

    // Proxy URL prefix configuration
    new obsidian.Setting(containerEl)
      .setName('Proxy Server')
      .setDesc('The proxy server URL for accelerating GitHub requests. Must end with a slash.')
      .addText(text => text
        .setPlaceholder('https://gh-proxy.org/')
        .setValue(this.plugin.settings.proxyPrefix)
        .onChange(async (value) => {
          this.plugin.settings.proxyPrefix = value;
          await this.plugin.saveSettings();
          // Reinitialize proxy with new URL
          if (this.plugin.proxy) {
            this.plugin.proxy.unRegister();
            this.plugin.proxy = null;
          }
          this.plugin.initProxy();
        }));

    // Debug logging toggle
    new obsidian.Setting(containerEl)
      .setName('Enable Logging')
      .setDesc('Log proxy acceleration activities to console for debugging. (Ctrl+Shit+I)')
      .addToggle(toggle => toggle
        .setValue(this.plugin.settings.enableLogging)
        .onChange(async (value) => {
          this.plugin.settings.enableLogging = value;
          await this.plugin.saveSettings();
        }));

    // Configurable URLs to proxy
    const urlsContainer = containerEl.createEl('div', {cls: 'market-proxy-urls'});
    urlsContainer.createEl('h3', {text: 'URLs to Accelerate'});
    urlsContainer.createEl('p', {
      text: 'Configure which URLs should be accelerated through the proxy server. Each URL should be on a new line.'
    });
    
    new obsidian.Setting(containerEl)
      .setName('Proxied URLs')
      .setDesc('URL prefixes to accelerate (one per line)')
      .addTextArea(text => {
        text
          .setPlaceholder('https://github.com/\nhttps://raw.githubusercontent.com/')
          .setValue(this.plugin.settings.proxiedUrls.join('\n'))
          .onChange(async (value) => {
            // Parse textarea into array, filtering out empty lines
            const urls = value.split('\n')
              .map(url => url.trim())
              .filter(url => url.length > 0);
            
            this.plugin.settings.proxiedUrls = urls;
            await this.plugin.saveSettings();
            
            // Reinitialize proxy with new URL list
            if (this.plugin.proxy) {
              this.plugin.proxy.unRegister();
              this.plugin.proxy = null;
            }
            this.plugin.initProxy();
          });
        text.inputEl.rows = 6;
        text.inputEl.cols = 50;
      });

    // Information section
    containerEl.createEl('p', {
      text: 'Note: Changes to proxy settings require reloading the proxy. This happens automatically when you change settings.'
    });

    // Examples section
    const exampleContainer = containerEl.createEl('div', {cls: 'market-proxy-example'});
    exampleContainer.createEl('h3', {text: 'Acceleration Examples'});
    exampleContainer.createEl('p', {
      text: '• https://github.com/user/repo → https://gh-proxy.org/https://github.com/user/repo'
    });
    exampleContainer.createEl('p', {
      text: '• https://raw.githubusercontent.com/user/repo/main/file.md → https://gh-proxy.org/https://raw.githubusercontent.com/user/repo/main/file.md'
    });
    
    // Popular proxy services
    const servicesContainer = containerEl.createEl('div', {cls: 'market-proxy-services'});
    servicesContainer.createEl('h3', {text: 'Recommended Proxy Services'});
    servicesContainer.createEl('p', {
      text: '• https://gh-proxy.org/ (fast & reliable)'
    });
    servicesContainer.createEl('p', {
      text: '• https://mirror.ghproxy.com/'
    });
    servicesContainer.createEl('p', {
      text: '• https://ghproxy.com/'
    });
  }
}

// Main plugin class
class MarketProxy extends obsidian.Plugin {
  constructor(app, manifest) {
    super(app, manifest);
    this.settings = null;
    this.proxy = null;
  }
  
  async loadSettings() {
    try {
      // Try to load existing settings
      const savedData = await this.loadData();
      if (savedData) {
        // Ensure proxiedUrls exists and is an array
        if (!savedData.proxiedUrls || !Array.isArray(savedData.proxiedUrls)) {
          savedData.proxiedUrls = DEFAULT_SETTINGS.proxiedUrls;
        }
        
        // Merge saved settings with defaults
        this.settings = Object.assign({}, DEFAULT_SETTINGS, savedData);
      } else {
        // Use default settings if no saved data
        this.settings = Object.assign({}, DEFAULT_SETTINGS);
        // Save default settings
        await this.saveData(this.settings);
      }
    } catch (error) {
      // Fallback to default settings on any error
      console.error("MarketProxy: Failed to load settings, using defaults", error);
      this.settings = Object.assign({}, DEFAULT_SETTINGS);
      // Try to save defaults
      try {
        await this.saveData(this.settings);
      } catch (saveError) {
        console.error("MarketProxy: Failed to save default settings", saveError);
      }
    }
  }

  async saveSettings() {
    try {
      // Ensure proxiedUrls is always an array
      if (!this.settings.proxiedUrls || !Array.isArray(this.settings.proxiedUrls)) {
        this.settings.proxiedUrls = DEFAULT_SETTINGS.proxiedUrls;
      }
      
      await this.saveData(this.settings);
    } catch (error) {
      console.error("MarketProxy: Failed to save settings", error);
    }
  }
  
  // Initialize proxy based on platform and settings
  initProxy() {
    try {
      if (this.settings && this.settings.enableProxy) {
        if (obsidian.Platform.isDesktop) {
          this.proxy = new AppProxy(this.settings);
        } else {
          this.proxy = new NativeProxy(this.settings);
        }
        
        if (this.proxy) {
          this.proxy.register();
          if (this.settings.enableLogging) {
            console.log("MarketProxy: Proxy initialized for URLs:", this.settings.proxiedUrls);
            console.log("MarketProxy: Using proxy server:", this.settings.proxyPrefix);
          }
        }
      }
    } catch (error) {
      console.error("MarketProxy: Proxy initialization failed", error);
    }
  }

  async onload() {
    console.log("MarketProxy: Loading GitHub acceleration proxy plugin...");
    
    try {
      // Load settings first
      await this.loadSettings();
      
      // Initialize proxy with current settings
      this.initProxy();
      
      // Add settings tab to Obsidian settings
      this.addSettingTab(new MarketProxySettingTab(this.app, this));
      
      console.log("MarketProxy: Plugin loaded successfully");
      console.log("MarketProxy: Accelerating URLs:", this.settings.proxiedUrls);
    } catch (error) {
      console.error("MarketProxy: Failed to load plugin", error);
      // Even if there's an error, try to at least initialize with defaults
      if (!this.settings) {
        this.settings = Object.assign({}, DEFAULT_SETTINGS);
        this.initProxy();
      }
    }
  }
  
  onunload() {
    console.log("MarketProxy: Unloading plugin...");
    
    // Clean up proxy handlers
    if (this.proxy) {
      this.proxy.unRegister();
    }
    
    console.log("MarketProxy: Plugin unloaded");
  }
}

// Export for Obsidian
module.exports = MarketProxy;
module.exports.default = MarketProxy;